name: PHPStan

on:
  push:
    branches: [5.0, 5.1, 5.2]
  pull_request:
    branches: [5.0, 5.1, 5.2]
  workflow_dispatch:

jobs:
  PHPStan:

    strategy:
      fail-fast: false
      matrix:
        php_versions: ['8.1', '8.2', '8.3', '8.4', '8.5']

    runs-on: ubuntu-latest
    name: PHPStan - ${{ matrix.php_versions }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php_versions }}

    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse
