# GitHub Actions Workflow template for PHPStan Testing.
# Uncomment the "on" section below to enable PHPStan testing on GitHub Actions on push.

name: PHPStan

on:
#   push:
#     branches: ['*'] # Apply to all branches. List specific branches if needed.
#   pull_request:
#     branches: ['*'] # Apply to all branches. List specific branches if needed.
  workflow_dispatch:

jobs:
  PHPStan:
    strategy:
      fail-fast: false
      matrix:
        php_versions: ['8.1', '8.2', '8.3', '8.4', '8.5'] # PHP versions to test against
    runs-on: ubuntu-latest
    name: PHPStan - ${{ matrix.php_versions }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_versions }}

      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse
